SET @@auto_increment_increment=100000;

ALTER TABLE ORDERS MODIFY COLUMN ORDER_ID BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE ORDERS AUTO_INCREMENT=100000;

CREATE TABLE `CODES` (
  `code_id` int(10) NOT NULL,
  `code` varchar(15) NOT NULL,
  `issued` tinyint(4) DEFAULT NULL,
  `redeamed` tinyint(4) DEFAULT NULL,
  `DATE_CREATED` datetime DEFAULT NULL,
  `DATE_MODIFIED` datetime DEFAULT NULL,
  `UPDT_ID` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE ORDER_TOTAL DROP FOREIGN KEY 	FK2C983AD3EB69D4B6;
ALTER TABLE ATOM_TRANSACTION_RESPONSE DROP FOREIGN KEY FKACF37AD0EB69D4B6;
ALTER TABLE ORDER_PRODUCT DROP FOREIGN KEY FK98B580BEEB69D4B6;
ALTER TABLE ORDER_STATUS_HISTORY DROP FOREIGN KEY FK536CA658EB69D4B6;
ALTER TABLE PAYTM_TRANSACTION_RESPONSE DROP FOREIGN KEY FK9FDD3D20EB69D4B6;
ALTER TABLE SM_TRANSACTION DROP FOREIGN KEY FKD3321859EB69D4B6;


ALTER TABLE ORDER_TOTAL ADD CONSTRAINT FK2C983AD3EB69D4B6 FOREIGN KEY (order_id) REFERENCES ORDERS(order_id);
ALTER TABLE ATOM_TRANSACTION_RESPONSE ADD CONSTRAINT FKACF37AD0EB69D4B6 FOREIGN KEY (order_id) REFERENCES ORDERS(order_id);
ALTER TABLE ORDER_PRODUCT ADD CONSTRAINT FK98B580BEEB69D4B6 FOREIGN KEY (order_id) REFERENCES ORDERS(order_id);
ALTER TABLE ORDER_STATUS_HISTORY ADD CONSTRAINT FK536CA658EB69D4B6 FOREIGN KEY (order_id) REFERENCES ORDERS(order_id);
ALTER TABLE PAYTM_TRANSACTION_RESPONSE ADD CONSTRAINT FK9FDD3D20EB69D4B6 FOREIGN KEY (order_id) REFERENCES ORDERS(order_id);
ALTER TABLE SM_TRANSACTION ADD CONSTRAINT FKD3321859EB69D4B6 FOREIGN KEY (order_id) REFERENCES ORDERS(order_id);

ALTER TABLE `ORDERS` ADD `code_id` INT(10) NULL AFTER `MERCHANTID`, ADD INDEX `ORDERS_CODE_ID` (`code_id`);
ALTER TABLE ORDERS ADD CONSTRAINT FKORDERSCODE FOREIGN KEY (code_id) REFERENCES CODES(code_id);

TABLE `CODES` ADD INDEX(`code`);
ALTER TABLE `CODES` ADD UNIQUE(`code`);

ALTER TABLE `ORDER_PRODUCT` ADD `code_id` INT(10) NULL AFTER `PROMOTIONAL_VOUCHER_ID`, ADD UNIQUE `ORDER_PRODUCT_CODE_ID` (`code_id`);
ALTER TABLE ORDER_PRODUCT ADD CONSTRAINT FKORDERPRODUCTCODE FOREIGN KEY (code_id) REFERENCES CODES(code_id);

ALTER TABLE `PRODUCT_DESCRIPTION` ADD `PRODUCT_PRICE_HIGHLIGHT` VARCHAR(512) NULL AFTER `PRODUCT_ID`;