package com.salesmanager.core.business.payments.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import org.json.simple.JSONAware;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.salesmanager.core.business.common.model.audit.AuditListener;
import com.salesmanager.core.business.common.model.audit.AuditSection;
import com.salesmanager.core.business.common.model.audit.Auditable;
import com.salesmanager.core.business.generic.model.SalesManagerEntity;
import com.salesmanager.core.business.order.model.Order;
import com.salesmanager.core.constants.SchemaConstant;

@Entity
@EntityListeners(value = AuditListener.class)
@Table(name = "ATOM_TRANSACTION_RESPONSE", schema= SchemaConstant.SALESMANAGER_SCHEMA)
public class AtomTxnResponse extends SalesManagerEntity<Long, AtomTxnResponse> implements Serializable, Auditable, JSONAware{

	private static final Logger LOGGER = LoggerFactory.getLogger(AtomTxnResponse.class);
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ATOM_TXN_RESPONSE_ID")
	@TableGenerator(name = "TABLE_GEN", table = "SM_SEQUENCER", pkColumnName = "SEQ_NAME", valueColumnName = "SEQ_COUNT", pkColumnValue = "ATOM_TXN_SEQ_NEXT_VAL")
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "TABLE_GEN")
	private Long id;
	
	/*
	 * Atom Transaction id generated by Atom
	 */
	@Column(name="mmp_txn")
	private String mmpTxn;
	
	/*
	 * Merchant transaction id
	 */
	@Column(name="mer_txn")
	private String mertxn;
	
	/*
	 * Amount approved by atom
	 */
	@Column(name="amt")
	private BigDecimal amt;
	
	/*
	 * Product id for Atom
	 */
	@Column(name="prod")
	private String prodId;
	
	/*
	 * Date and timestamp of transaction
	 */
	@Column(name="date")
	private String date;
	
	/*
	 * Bank transaction id generated by bank
	 */
	@Column(name="bank_txn")
	private String bankTxn;
	
	
	/*
	 * PG response OK for success and f for fail
	 */
	@Column(name="f_code")
	private String fCode;
	
	/*
	 * Client id sent by merchant
	 */
	@Column(name="clientcode")
	private String clientCode;
	
	/*
	 * Bank in which transaction happened
	 */
	@Column(name="bank_name")
	private String bankName;
	
	@Column(name="merchant_id")
	private String merchantId;
	
	/*
	 * Merchant data
	 */
	@Column(name="udf9")
	private String udf9;
	
	/*
	 * Payment Channel NB,CC,DC,IM,MX
	 */
	@Column(name="discriminator")
	private String discriminator;
	
	@Column(name="surcharge")
	private String surcharge;
	
	@Column(name="CardNumber")
	private String CardNumber;
	
	/*
	 * Customer Name
	 */
	@Column(name="udf1")
	private String udf1;
	
	/*
	 * Customer email id
	 */
	@Column(name="udf2")
	private String udf2;
	
	/*
	 * Customer mobile number
	 */
	@Column(name="udf3")
	private String udf3;
	
	/*
	 * Billing address
	 */
	@Column(name="udf4")
	private String udf4;
	
	/*
	 * Merchant data
	 */
	@Column(name="udf5")
	private String udf5;
	
	/*
	 * Merchant data
	 */
	@Column(name="udf6")
	private String udf6;
	
	/*
	 * transaction failure reason
	 */
	@Column(name="description")
	private String description;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="ORDER_ID", nullable=true)
	private Order order;
	
	@Embedded
	private AuditSection auditSection = new AuditSection();
	
	
	@Override
	public String toJSONString() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public AuditSection getAuditSection() {
		return this.auditSection;
	}

	@Override
	public void setAuditSection(AuditSection audit) {
		this.auditSection = audit;
	}

	@Override
	public Long getId() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setId(Long id) {
		// TODO Auto-generated method stub
		
	}

	public String getMmpTxn() {
		return mmpTxn;
	}

	public void setMmpTxn(String mmpTxn) {
		this.mmpTxn = mmpTxn;
	}

	public String getMertxn() {
		return mertxn;
	}

	public void setMertxn(String mertxn) {
		this.mertxn = mertxn;
	}

	public BigDecimal getAmt() {
		return amt;
	}

	public void setAmt(BigDecimal amt) {
		this.amt = amt;
	}

	public String getProdId() {
		return prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

	public String getBankTxn() {
		return bankTxn;
	}

	public void setBankTxn(String bankTxn) {
		this.bankTxn = bankTxn;
	}

	public String getfCode() {
		return fCode;
	}

	public void setfCode(String fCode) {
		this.fCode = fCode;
	}

	public String getClientCode() {
		return clientCode;
	}

	public void setClientCode(String clientCode) {
		this.clientCode = clientCode;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getMerchantId() {
		return merchantId;
	}

	public void setMerchantId(String merchantId) {
		this.merchantId = merchantId;
	}

	public String getUdf9() {
		return udf9;
	}

	public void setUdf9(String udf9) {
		this.udf9 = udf9;
	}

	public String getDiscriminator() {
		return discriminator;
	}

	public void setDiscriminator(String discriminator) {
		this.discriminator = discriminator;
	}

	public String getSurcharge() {
		return surcharge;
	}

	public void setSurcharge(String surcharge) {
		this.surcharge = surcharge;
	}

	public String getCardNumber() {
		return CardNumber;
	}

	public void setCardNumber(String cardNumber) {
		CardNumber = cardNumber;
	}

	public String getUdf1() {
		return udf1;
	}

	public void setUdf1(String udf1) {
		this.udf1 = udf1;
	}

	public String getUdf2() {
		return udf2;
	}

	public void setUdf2(String udf2) {
		this.udf2 = udf2;
	}

	public String getUdf3() {
		return udf3;
	}

	public void setUdf3(String udf3) {
		this.udf3 = udf3;
	}

	public String getUdf4() {
		return udf4;
	}

	public void setUdf4(String udf4) {
		this.udf4 = udf4;
	}

	public String getUdf5() {
		return udf5;
	}

	public void setUdf5(String udf5) {
		this.udf5 = udf5;
	}

	public String getUdf6() {
		return udf6;
	}

	public void setUdf6(String udf6) {
		this.udf6 = udf6;
	}

	public Order getOrder() {
		return order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
